[mypy]
exclude = alembic/
python_version = 3.14
strict = False
ignore_missing_imports = True
disable_error_code = import-untyped
warn_unused_ignores = True
warn_redundant_casts = True
warn_return_any = True
no_implicit_optional = True
check_untyped_defs = True
