"""add reply_to_id to message

Revision ID: 098628e7216f
Revises: f1aa447576d1
Create Date: 2026-07-30 14:33:15.822386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098628e7216f'
down_revision: Union[str, Sequence[str], None] = 'f1aa447576d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'message', 'message', ['reply_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'reply_to_id')
    # ### end Alembic commands ###
