"""add forward fields to message and pinned_message_id to chat_group

Revision ID: 3884a6a57eb1
Revises: 8d03f0b6ad18
Create Date: 2026-08-04 12:03:27.843519

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3884a6a57eb1"
down_revision: Union[str, Sequence[str], None] = "8d03f0b6ad18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_group", sa.Column("pinned_message_id", sa.Integer(), nullable=True))
    op.add_column("message", sa.Column("forwarded_from_id", sa.Integer(), nullable=True))
    op.add_column("message", sa.Column("forwarded_group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        "fk_message_forwarded_from_id",
        "message",
        "message",
        ["forwarded_from_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_message_forwarded_from_id", "message", type_="foreignkey")
    op.drop_column("message", "forwarded_group_id")
    op.drop_column("message", "forwarded_from_id")
    op.drop_column("chat_group", "pinned_message_id")
    # ### end Alembic commands ###
