"""add is_direct to chat_group

Revision ID: 8d03f0b6ad18
Revises: 098628e7216f
Create Date: 2026-08-04 11:13:20.583789

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d03f0b6ad18"
down_revision: Union[str, Sequence[str], None] = "098628e7216f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_group",
        sa.Column("is_direct", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_group", "is_direct")
    # ### end Alembic commands ###
