"""message_edit_history

Revision ID: 9c77988df9b3
Revises: c69712938c7f
Create Date: 2026-08-07 14:05:28.988405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9c77988df9b3"
down_revision: Union[str, Sequence[str], None] = "c69712938c7f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("edited_at", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_message_version_message_id"), "message_version", ["message_id"], unique=False
    )
    op.add_column(
        "message", sa.Column("edited_at", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "edited_at")
    op.drop_index(op.f("ix_message_version_message_id"), table_name="message_version")
    op.drop_table("message_version")
    # ### end Alembic commands ###
