"""add date_of_birth to user

Revision ID: f1aa447576d1
Revises: ddd788bb0416
Create Date: 2026-07-30 13:55:29.182652

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1aa447576d1"
down_revision: Union[str, Sequence[str], None] = "ddd788bb0416"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("date_of_birth", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "date_of_birth")
    # ### end Alembic commands ###
